module.exports = {
    'AccessDenied': true,
    'DarkMagicianGirl': true,
    'Irate': true,
    'Mele': true,
    'Morgan LeFlay': true,
    'Omni~Mage': true,
    'OneShot': true,
    'ParryDox': true,
    'Reach': true,
    'StormWolf': true,
    'Trinity': true,
    'Vyro': true,
    'WestCoastKiwiw': true,
    'Academia': true,
    'Black Ballista': true,
    'HelixReactor': true,
    'Laughing Luna': true,
    'Lignes': true,
    'Ragna_Edge': true,
    '[ Jojooo. ]': true,
    'Kironix': true
};